#!/usr/bin/env bash

set -e

# We add this in the user config because it's not straight-forward to restart a nix-daemon in a cotainer (it doesn't have systemd).
mkdir -p ~/.config/nix
echo "experimental-features = nix-command flakes" > ~/.config/nix/nix.conf


# curl -LsSf https://astral.sh/uv/install.sh | sh
# 
# echo 'export PATH="/home/vscode/.local/bin:$PATH"' >> ~/.bashrc
# # Install Python using uv
# /home/vscode/.local/bin/uv python install 3.12